### ISSUE TITLE
评估参考

### ISSUE THREAD

**Issue by haidequanbu** [X-D-Lab/MindChat#10]
作者：
       你们好，非常感谢你们这项工作对心理大模型开源社区的贡献。
       想请问模型训练完之后，如何进行训练效果的评估？
       另外想请问下，readme下面这张图里面的评估的对象是与模型正在聊天的人吗？
<img width="841" alt="image" src="https://github.com/X-D-Lab/MindChat/assets/67882439/b4af5a2d-7f8c-4175-8f8c-e0f9935d5823">
       期待您的回复！

**Comment by thomas-yanxin** [comment]
针对评估方式由三个部分组成：基于内部benchmark用GPT4做自动化测评把、用户的真实使用反馈、少数的专业心理咨询师的反馈建议。
当然对于此场景来说，模型效果的评价可能较为主观，用户与用户之间的差异也许较大。我们也在积极探索更优、更科学和更短周期的评价方式。

是与模型对话的用户。我们希望对于心理评测能以更加自然、更加隐藏、更加日常的方式进行，从而达到更加客观的结果。当然，关于心理评测与大语言模型的结合我们还在探索中。

感谢您的提问！我们还在持续迭代中，欢迎反馈和交流。

**Comment by haidequanbu** [comment]
感谢作者回复！
