### ISSUE TITLE
训练数据和训练代码开源问题

### ISSUE THREAD

**Issue by zlszhonglongshen** [X-D-Lab/MindChat#13]
大佬们什么时候有开源计划？

**Comment by thomas-yanxin** [comment]
感谢您的关注呀！训练数据因为合作方的权限问题暂时无法开源，当然可能后续有时间会把我们内部对于心理数据的处理过程开源，不过要时间整理一下。训练代码可直接复用开源社区的训练框架，诸如Llama_Factory,xtuner,swift等都是非常有特色的工作。
