### ISSUE TITLE
大佬们，什么时候可以先搞个 openai_api文件 就可以接接口了呀

### ISSUE THREAD

**Issue by zlszhonglongshen** [X-D-Lab/MindChat#14]
大佬们，什么时候可以先搞个 openai_api文件 就可以接接口了呀

**Comment by thomas-yanxin** [comment]
感谢关注呀！部署的时候可以直接用FastChat或者其他部署框架，都是支持openai_api的，稍后我可以更新一下部署教程给大家。如果有什么需要帮助或者合作的可以邮箱联系我。

**Comment by thomas-yanxin** [comment]
写了一个教程，你可以[参考](https://github.com/X-D-Lab/MindChat/blob/main/docs/inference.md#%E6%A8%A1%E5%9E%8B%E6%9C%8D%E5%8A%A1)
