### ISSUE TITLE
请问训练MindChat-Qwen-7B-v2模型，训练数据做了预处理了吗

### ISSUE THREAD

**Issue by wangyao123456a** [X-D-Lab/MindChat#15]
MindChat-Qwen-7B-v2 的模型是基于qwen-7b 吗？我看qwen-7b 训练前会把数据预处理成下边格式：
<|im_start|>system\nYou are a helpful assistant.<|im_end|>\n
<|im_start|>user\n你好<|im_end|>\n
<|im_start|>assistant\n你好！很高兴为你提供帮助。<|im_end|>\n
<|im_start|>user\n给我讲一个年轻人奋斗创业最终取得成功的故事。<|im_end|>\n
<|im_start|>assistant\n
请问咱们会对数据也做一样处理吗？
我看提供的推理代码也没有做数据前处理。https://github.com/X-D-Lab/MindChat/tree/main/scripts
所以我想确认下最终咱们训练数据是做成什么格式？

**Comment by thomas-yanxin** [comment]
MindChat模型的templete follow qwen的templete。目前scripts里面提供的脚本是推理脚本，旨在帮助用户更快地尝试MindChat模型。如果您需要模型微调的帮助，可以参考https://github.com/X-D-Lab/MindChat/issues/13#issuecomment-1899835276 的回答。
