### ISSUE TITLE
你好，能介绍一下数据集的构建吗

### ISSUE THREAD

**Issue by mie-zhz** [X-D-Lab/MindChat#22]
想了解下你们怎么获取的原始文本和怎么构建自动化流程生成对话

**Comment by D-Mahony-X** [comment]
4月24日19:00-20:00在机器之心SOTA上有一场关于数据构建、微调与案例分享的直播，届时会介绍相关细节，敬请关注。直播信息近日会在主页和用户微信群中发布。

**Comment by han508** [comment]
交流群二维码过期了

**Comment by D-Mahony-X** [comment]
[image: 微信图片_20240423124444.jpg]

Ze Han ***@***.***> 于2024年4月22日周一 14:20写道：
