### ISSUE TITLE
模型如何使用？

### ISSUE THREAD

**Issue by zhangjh** [X-D-Lab/MindChat#5]
项目readme貌似只有相关介绍，并未提供模型使用方式？

**Comment by thomas-yanxin** [comment]
提供了简易的[webui](https://github.com/X-D-Lab/MindChat/blob/main/webui_demo.py)代码。模型推理代码遵循各个原模型。

**Comment by thomas-yanxin** [comment]
增加了MindChat-Qwen-7B-v2的[示例代码](https://github.com/X-D-Lab/MindChat/tree/main/scripts)供参考，分别提供了huggingface和modelscope两种使用方式。

**Comment by zhangjh** [comment]
Thank you
