### ISSUE TITLE
加载MindChat-Baichuan-13B的模型会出错

### ISSUE THREAD

**Issue by WonDaniel** [X-D-Lab/MindChat#7]
报错是
AttributeError: 'BaichuanTokenizer' object has no attribute 'sp_model'

**Comment by WonDaniel** [comment]
使用webui_demo.py修改的模型路径来加载的。
目前发现这个sp_model的问题，是需要在baichuan的目录内tokenization_baichuan.py，将BaichuanTokenizer的super().__init__放在最下面就可以了。
但是解决这个问题后还是会有加载权重的参数问题，比如AutoModelForCausalLM.from_pretrained没有fp16，model.chat没有history，也就是提供的webui_demo.py并不适用baichuan

**Comment by thomas-yanxin** [comment]
控制一下transformers的版本即可，具体可自行搜索。另外mindchat-baichuan的实际效果可能不如mindchat-qwen，建议用后者。
